### ISSUE TITLE
Support ForEach

### ISSUE THREAD

**Issue by melgu** [fredyshox/PageView#17]
When using the HPageView with sperate views, it works as expected:
```swift
HPageView(selectedPage: $pageIndex) {
	Color.red
	Color.green
	Color.blue
}
```

But when trying to use ForEach, the PageView looks strange and only has one page indicator dot:
```swift
HPageView(selectedPage: $pageIndex, theme: pageTheme) {
	ForEach(0..<2) { n in
		Text("Number \(n)")
	}
}
```
<img width="467" alt="Bildschirmfoto 2021-06-01 um 15 35 41" src="https://user-images.githubusercontent.com/9601403/120332431-07470800-c2ef-11eb-98bd-31151c04393e.png">

**Comment by fredyshox** [comment]
ForEach-like init was added in release 1.5.0
