### ISSUE TITLE
(watchOS) usability issue in HPageView

### ISSUE THREAD

**Issue by d1l4y** [fredyshox/PageView#2]
hey, I'm building an watchOS app using swiftUI and PageView, 
the first view inside the HPageView has two buttons inside a VStack, and it's almost impossible to swipe from this view to another, because every time that I try to swipe, it's recognized as a button click

**Comment by fredyshox** [comment]
This seems to be an issue with gesture precedence, I'm looking into that in #3

**Comment by fredyshox** [comment]
Fixed in 1.3.1
