### ISSUE TITLE
Set position of dots to right in VPageView.

### ISSUE THREAD

**Issue by takasurazeem** [fredyshox/PageView#25]
Is there a property to flip this behaviour? Right now dots appear on the left side only 
<img width="431" alt="image" src="https://user-images.githubusercontent.com/2876680/230771871-0e6d9626-9635-47ea-844f-12c1cc52e780.png">

**Comment by fredyshox** [comment]
There's `alignment` property of [PageControlTheme](https://github.com/fredyshox/PageView#theme).
