### ISSUE TITLE
Change navigationBarTitle on page switch

### ISSUE THREAD

**Issue by kushsolitary** [fredyshox/PageView#8]
Hi, is there a way to animate/change the `.navigationBarTitle` on page switch? Currently, it takes the title of the first page and displays that on all the other pages as well.

**Comment by fredyshox** [comment]
With support for current page binding in 1.4.0, you can dynamically change title from superview like this: 

```swift
@State var pageIndex: Int

...

var body: some View {
    HPageView(selectedPage: $pageIndex) {
        ...
    }.navigationBarTitle(title(for: pageIndex))
}

func title(for pageIndex: Int) -> String {
    // return title string based on currently displayed title
}
```
